# Generated by Django 5.1.15 on 2026-07-06 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heritage', '0005_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='User-defined title or name of the voyage.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the voyage was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the voyage was last updated.')),
                ('user', models.ForeignKey(help_text='The user who created and owns this voyage.', on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoyageStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(help_text='The sequential position of the stop (0-indexed).')),
                ('site', models.ForeignKey(help_text='The historical site associated with this stop.', on_delete=django.db.models.deletion.CASCADE, related_name='voyage_stops', to='heritage.historicalsite')),
                ('voyage', models.ForeignKey(help_text='The parent voyage this stop belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='voyages.voyage')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('voyage', 'order_index')},
            },
        ),
    ]
