# Generated by Django 5.1.15 on 2026-07-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0006_country_historicalsite_country_new'),
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='focus_country',
            field=models.ForeignKey(blank=True, help_text='The country this voyage focuses on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages', to='heritage.country'),
        ),
    ]
