# Generated by Django 5.1.15 on 2026-07-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_voyage_focus_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='focus_city',
            field=models.CharField(blank=True, help_text='The specific city this voyage focuses on.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='focus_city_bbox',
            field=models.JSONField(blank=True, help_text='Bounding box of the focused city: [south, west, north, east]', null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='focus_city_latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinates of the focused city.', null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='focus_city_longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinates of the focused city.', null=True),
        ),
    ]
