# Generated by Django 5.1.15 on 2026-06-25 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site_type', models.CharField(choices=[('castle', 'Castle'), ('ruins', 'Ruins'), ('monument', 'Monument'), ('holy_site', 'Holy Site'), ('archaeological', 'Archaeological Site'), ('other', 'Other')], default='other', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('wikidata', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
