# Generated by Django 5.1.15 on 2026-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='english_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
