# Generated by Django 5.1.15 on 2026-06-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_historicalsite_english_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='osm_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='osm_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
