# Generated by Django 5.1.15 on 2026-06-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0003_historicalsite_osm_id_historicalsite_osm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
