# Generated by Django 5.1.15 on 2026-07-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0007_migrate_countries'),
    ]

    operations = [
        # 1. Delete the old country CharField
        migrations.RemoveField(
            model_name='historicalsite',
            name='country',
        ),
        # 2. Rename country_new ForeignKey to country
        migrations.RenameField(
            model_name='historicalsite',
            old_name='country_new',
            new_name='country',
        ),
        # 3. Make the renamed country ForeignKey non-nullable
        migrations.AlterField(
            model_name='historicalsite',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='heritage.country'),
        ),
    ]
