# Generated by Django 5.1.15 on 2026-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0008_remove_historicalsite_country_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='bbox',
            field=models.JSONField(blank=True, help_text='Bounding box: [south, west, north, east]', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
