# Generated by Django 5.1.15 on 2026-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0009_alter_country_bbox_alter_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='address',
            field=models.TextField(blank=True, help_text='Full formatted address derived from reverse geocoding', null=True),
        ),
    ]
